// Zero-dependency bundler: turns the ESM sources under src/ into one plain
// <script> (a CommonJS-style module map + require shim), so the packaged
// demo works when the HTML file is opened directly (double-clicked) instead
// of served over HTTP. Browsers refuse to fetch `type="module"` scripts from
// a `file://` page, which is why `examples/vanilla.html` used to render
// nothing at all when opened that way.
//
// Source stays plain ESM for real consumers (bundlers, `import` in an app);
// this script only produces the throwaway demo bundle under dist/.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(root, 'src');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? walk(full) : full.endsWith('.js') ? [full] : [];
  });
}

function keyFor(absPath) {
  return path.relative(srcDir, absPath).split(path.sep).join('/');
}

function resolveImport(fromKey, spec) {
  const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(fromKey), spec));
  return resolved;
}

/** `a, b as c` -> `a, b: c` -- the destructuring-assignment spelling of a rename. */
function destructure(names) {
  return names.split(',').map((n) => n.trim()).filter(Boolean)
    .map((n) => n.replace(/^([A-Za-z0-9_$]+)\s+as\s+([A-Za-z0-9_$]+)$/, '$1: $2'))
    .join(', ');
}

function localNames(names) {
  return names.split(',').map((n) => n.trim()).filter(Boolean)
    .map((n) => { const m = n.match(/^[A-Za-z0-9_$]+\s+as\s+([A-Za-z0-9_$]+)$/); return m ? m[1] : n; });
}

function transform(key, src) {
  const exported = new Set();
  let out = src.replace(/^import\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?$/gm, (_, names, spec) => {
    const target = resolveImport(key, spec);
    return `const {${destructure(names)}} = __require(${JSON.stringify(target)});`;
  });

  out = out.replace(/^export\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?$/gm, (_, names, spec) => {
    const target = resolveImport(key, spec);
    const list = localNames(names);
    list.forEach((n) => exported.add(n));
    return `const {${destructure(names)}} = __require(${JSON.stringify(target)});`;
  });

  out = out.replace(/^export\s+(const|function|class|async function)\s+([A-Za-z0-9_$]+)/gm, (_, kind, name) => {
    exported.add(name);
    return `${kind} ${name}`;
  });

  const leftover = out.match(/^export\s+/m);
  if (leftover) throw new Error(`${key}: unhandled export syntax near "${leftover[0]}"`);
  if (/^import\s+/m.test(out)) throw new Error(`${key}: unhandled import syntax`);

  return `${out}\nObject.assign(exports, { ${[...exported].join(', ')} });\n`;
}

const files = walk(srcDir);
const modules = files.map((f) => {
  const key = keyFor(f);
  const body = transform(key, fs.readFileSync(f, 'utf8'));
  return `__modules[${JSON.stringify(key)}] = function(module, exports, __require) {\n${body}\n};`;
});

const bundle = `// GENERATED by build.js -- do not edit by hand. Re-run \`node build.js\`.
(function () {
  var __modules = {};
  var __cache = {};
  function __require(key) {
    if (__cache[key]) return __cache[key].exports;
    var module = { exports: {} };
    __cache[key] = module;
    __modules[key](module, module.exports, __require);
    return module.exports;
  }
${modules.join('\n')}
  window.MailCraftEditorBundle = __require('index.js');
})();
`;

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist', 'mailcraft-editor.bundle.js'), bundle);
console.log(`Wrote dist/mailcraft-editor.bundle.js (${files.length} modules, ${bundle.length} bytes)`);
