// Zero-dependency bundler: turns the ESM sources under src/ into one plain
// <script> (a CommonJS-style module map + require shim), so the packaged
// demo works when the HTML file is opened directly (double-clicked) instead
// of served over HTTP. Browsers refuse to fetch `type="module"` scripts from
// a `file://` page, which is why `examples/vanilla.html` used to render
// nothing at all when opened that way.
//
// Source stays plain ESM for real consumers (bundlers, `import` in an app);
// this script only produces the throwaway demo bundle under dist/.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const root = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(root, 'src');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? walk(full) : full.endsWith('.js') ? [full] : [];
  });
}

function keyFor(absPath) {
  return path.relative(srcDir, absPath).split(path.sep).join('/');
}

function resolveImport(fromKey, spec) {
  const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(fromKey), spec));
  return resolved;
}

/** `a, b as c` -> `a, b: c` -- the destructuring-assignment spelling of a rename. */
function destructure(names) {
  return names.split(',').map((n) => n.trim()).filter(Boolean)
    .map((n) => n.replace(/^([A-Za-z0-9_$]+)\s+as\s+([A-Za-z0-9_$]+)$/, '$1: $2'))
    .join(', ');
}

function localNames(names) {
  return names.split(',').map((n) => n.trim()).filter(Boolean)
    .map((n) => { const m = n.match(/^[A-Za-z0-9_$]+\s+as\s+([A-Za-z0-9_$]+)$/); return m ? m[1] : n; });
}

function transform(key, src) {
  const exported = new Set();
  let out = src.replace(/^import\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?$/gm, (_, names, spec) => {
    const target = resolveImport(key, spec);
    return `const {${destructure(names)}} = __require(${JSON.stringify(target)});`;
  });

  out = out.replace(/^export\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?$/gm, (_, names, spec) => {
    const target = resolveImport(key, spec);
    const list = localNames(names);
    list.forEach((n) => exported.add(n));
    return `const {${destructure(names)}} = __require(${JSON.stringify(target)});`;
  });

  out = out.replace(/^export\s+(const|function|class|async function)\s+([A-Za-z0-9_$]+)/gm, (_, kind, name) => {
    exported.add(name);
    return `${kind} ${name}`;
  });

  // Literal dynamic imports (the lazy locale loaders) become synchronous
  // requires wrapped in a resolved promise: the demo bundle carries every
  // module anyway, so "load the French table" is a map lookup, and the
  // `import()` contract (a promise for the module namespace) is preserved.
  out = out.replace(/\bimport\(\s*(['"])([^'"]+)\1\s*\)/g, (_, q, spec) => `Promise.resolve(__require(${JSON.stringify(resolveImport(key, spec))}))`);

  const leftover = out.match(/^export\s+/m);
  if (leftover) throw new Error(`${key}: unhandled export syntax near "${leftover[0]}"`);
  if (/^import\s+/m.test(out)) throw new Error(`${key}: unhandled import syntax`);

  return `${out}\nObject.assign(exports, { ${[...exported].join(', ')} });\n`;
}

const files = walk(srcDir);
const modules = files.map((f) => {
  const key = keyFor(f);
  const body = transform(key, fs.readFileSync(f, 'utf8'));
  return `__modules[${JSON.stringify(key)}] = function(module, exports, __require) {\n${body}\n};`;
});

const bundle = `// GENERATED by build.js -- do not edit by hand. Re-run \`node build.js\`.
(function () {
  var __modules = {};
  var __cache = {};
  function __require(key) {
    if (__cache[key]) return __cache[key].exports;
    var module = { exports: {} };
    __cache[key] = module;
    __modules[key](module, module.exports, __require);
    return module.exports;
  }
${modules.join('\n')}
  window.MailCraftEditorBundle = __require('index.js');
})();
`;

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
const outFile = path.join(root, 'dist', 'mailcraft-editor.bundle.js');

/**
 * Minify with esbuild when it is installed, ship the readable bundle when it
 * is not.
 *
 * esbuild is a devDependency, never a runtime one -- nothing a consumer
 * installs changes, and `npm install mailcraft` still pulls in no transitive
 * packages. The fallback is what keeps that honest: a clone with no
 * node_modules still produces a working `dist/` with `node build.js`, exactly
 * as it did before, so the build is never blocked on a toolchain.
 *
 * The sourcemap is what makes minifying safe to do by default -- a stack trace
 * from a host's console still points at a line in src/.
 */
let output = bundle;
let note = 'not minified (esbuild not installed)';
try {
  const esbuild = createRequire(import.meta.url)('esbuild');
  const res = esbuild.transformSync(bundle, {
    minify: true,
    target: 'es2020',
    legalComments: 'none',
    // Without this esbuild escapes every non-ASCII character to \uXXXX, which
    // on this bundle is not a rounding error: the 31 shipped locale tables are
    // Arabic, Bengali, Dzongkha, Greek, Thai and more, and escaping them costs
    // ~130 KB of pure padding. The output is UTF-8 -- what a <script> in a
    // charset=utf-8 page, and every server default, already assumes.
    charset: 'utf8',
    sourcemap: true,
    sourcefile: 'mailcraft-editor.bundle.js',
  });
  output = res.code + '\n//# sourceMappingURL=mailcraft-editor.bundle.js.map\n';
  fs.writeFileSync(outFile + '.map', res.map);
  note = `minified, ${(100 - (Buffer.byteLength(output) / Buffer.byteLength(bundle)) * 100).toFixed(0)}% smaller, sourcemap alongside`;
} catch (e) {
  if (e && e.code !== 'MODULE_NOT_FOUND') throw e;
  try { fs.unlinkSync(outFile + '.map'); } catch { /* nothing to clear */ }
}

fs.writeFileSync(outFile, output);
console.log(`Wrote dist/mailcraft-editor.bundle.js (${files.length} modules, ${Buffer.byteLength(output)} bytes) -- ${note}`);

/**
 * Docs generation, in the same pass as the bundle so neither can drift:
 *
 * 1. The "Every message key" appendix in DOCS.md is rebuilt from the live EN
 *    table between the `message-keys` markers. The docs page is the only
 *    place a host without repo access can see the full key list, so it has
 *    to be generated, never hand-maintained -- test/system.test.mjs fails
 *    when the appendix and en.js disagree.
 *
 * 2. DOCS.md.txt / README.md.txt are byte-identical mirrors for the docs
 *    site. Jekyll turns every .md into a rendered .html page (and runs
 *    Liquid over it first), so the markdown source itself is otherwise
 *    unreachable to visitors -- these .txt copies are static files served
 *    verbatim, and they are what the site's "Copy for AI" button and
 *    llms.txt hand out.
 */
const { EN } = await import(pathToFileURL(path.join(srcDir, 'core', 'i18n', 'en.js')).href);
const docsPath = path.join(root, 'DOCS.md');
const docs = fs.readFileSync(docsPath, 'utf8');
const begin = docs.indexOf('<!-- message-keys:begin');
const beginEnd = docs.indexOf('-->', begin);
const end = docs.indexOf('<!-- message-keys:end -->', begin);
if (begin === -1 || end === -1) throw new Error('DOCS.md: message-keys markers not found');
// `|` is the only character in a value that can break a table row; keys are
// identifier-shaped and safe inside backticks.
const keyRows = Object.keys(EN).sort()
  .map((k) => `| \`${k}\` | ${String(EN[k]).replace(/\|/g, '\\|')} |`);
// The blank line before the closing marker is load-bearing: with the comment
// glued straight onto the last row, kramdown abandons the table and renders
// the whole block as one paragraph of pipes on the docs site.
const table = ['\n\n| key | English default |', '|---|---|', ...keyRows, '', ''].join('\n');
const updated = docs.slice(0, beginEnd + 3) + table + docs.slice(end);
if (updated !== docs) fs.writeFileSync(docsPath, updated);

for (const name of ['README.md', 'DOCS.md']) {
  const source = fs.readFileSync(path.join(root, name), 'utf8');
  const mirror = path.join(root, name + '.txt');
  if (!fs.existsSync(mirror) || fs.readFileSync(mirror, 'utf8') !== source) fs.writeFileSync(mirror, source);
}
console.log(`Wrote DOCS.md message-key appendix (${keyRows.length} keys) and the .md.txt site mirrors`);
