// Zero-dependency bundler: turns the ESM sources under src/ into one plain
// <script> (a CommonJS-style module map + require shim), so the packaged
// demo works when the HTML file is opened directly (double-clicked) instead
// of served over HTTP. Browsers refuse to fetch `type="module"` scripts from
// a `file://` page, which is why `examples/vanilla.html` used to render
// nothing at all when opened that way.
//
// Source stays plain ESM for real consumers (bundlers, `import` in an app);
// this script only produces the throwaway demo bundle under dist/.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const root = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(root, 'src');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? walk(full) : full.endsWith('.js') ? [full] : [];
  });
}

function keyFor(absPath) {
  return path.relative(srcDir, absPath).split(path.sep).join('/');
}

function resolveImport(fromKey, spec) {
  const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(fromKey), spec));
  return resolved;
}

/** `a, b as c` -> `a, b: c` -- the destructuring-assignment spelling of a rename. */
function destructure(names) {
  return names.split(',').map((n) => n.trim()).filter(Boolean)
    .map((n) => n.replace(/^([A-Za-z0-9_$]+)\s+as\s+([A-Za-z0-9_$]+)$/, '$1: $2'))
    .join(', ');
}

function localNames(names) {
  return names.split(',').map((n) => n.trim()).filter(Boolean)
    .map((n) => { const m = n.match(/^[A-Za-z0-9_$]+\s+as\s+([A-Za-z0-9_$]+)$/); return m ? m[1] : n; });
}

function transform(key, src) {
  const exported = new Set();
  let out = src.replace(/^import\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?$/gm, (_, names, spec) => {
    const target = resolveImport(key, spec);
    return `const {${destructure(names)}} = __require(${JSON.stringify(target)});`;
  });

  out = out.replace(/^export\s*\{([^}]*)\}\s*from\s*['"]([^'"]+)['"];?$/gm, (_, names, spec) => {
    const target = resolveImport(key, spec);
    const list = localNames(names);
    list.forEach((n) => exported.add(n));
    return `const {${destructure(names)}} = __require(${JSON.stringify(target)});`;
  });

  out = out.replace(/^export\s+(const|function|class|async function)\s+([A-Za-z0-9_$]+)/gm, (_, kind, name) => {
    exported.add(name);
    return `${kind} ${name}`;
  });

  const leftover = out.match(/^export\s+/m);
  if (leftover) throw new Error(`${key}: unhandled export syntax near "${leftover[0]}"`);
  if (/^import\s+/m.test(out)) throw new Error(`${key}: unhandled import syntax`);

  return `${out}\nObject.assign(exports, { ${[...exported].join(', ')} });\n`;
}

const files = walk(srcDir);
const modules = files.map((f) => {
  const key = keyFor(f);
  const body = transform(key, fs.readFileSync(f, 'utf8'));
  return `__modules[${JSON.stringify(key)}] = function(module, exports, __require) {\n${body}\n};`;
});

const bundle = `// GENERATED by build.js -- do not edit by hand. Re-run \`node build.js\`.
(function () {
  var __modules = {};
  var __cache = {};
  function __require(key) {
    if (__cache[key]) return __cache[key].exports;
    var module = { exports: {} };
    __cache[key] = module;
    __modules[key](module, module.exports, __require);
    return module.exports;
  }
${modules.join('\n')}
  window.MailCraftEditorBundle = __require('index.js');
})();
`;

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
const outFile = path.join(root, 'dist', 'mailcraft-editor.bundle.js');

/**
 * Minify with esbuild when it is installed, ship the readable bundle when it
 * is not.
 *
 * esbuild is a devDependency, never a runtime one -- nothing a consumer
 * installs changes, and `npm install mailcraft` still pulls in no transitive
 * packages. The fallback is what keeps that honest: a clone with no
 * node_modules still produces a working `dist/` with `node build.js`, exactly
 * as it did before, so the build is never blocked on a toolchain.
 *
 * The sourcemap is what makes minifying safe to do by default -- a stack trace
 * from a host's console still points at a line in src/.
 */
let output = bundle;
let note = 'not minified (esbuild not installed)';
try {
  const esbuild = createRequire(import.meta.url)('esbuild');
  const res = esbuild.transformSync(bundle, {
    minify: true,
    target: 'es2020',
    legalComments: 'none',
    // Without this esbuild escapes every non-ASCII character to \uXXXX, which
    // on this bundle is not a rounding error: the 31 shipped locale tables are
    // Arabic, Bengali, Dzongkha, Greek, Thai and more, and escaping them costs
    // ~130 KB of pure padding. The output is UTF-8 -- what a <script> in a
    // charset=utf-8 page, and every server default, already assumes.
    charset: 'utf8',
    sourcemap: true,
    sourcefile: 'mailcraft-editor.bundle.js',
  });
  output = res.code + '\n//# sourceMappingURL=mailcraft-editor.bundle.js.map\n';
  fs.writeFileSync(outFile + '.map', res.map);
  note = `minified, ${(100 - (Buffer.byteLength(output) / Buffer.byteLength(bundle)) * 100).toFixed(0)}% smaller, sourcemap alongside`;
} catch (e) {
  if (e && e.code !== 'MODULE_NOT_FOUND') throw e;
  try { fs.unlinkSync(outFile + '.map'); } catch { /* nothing to clear */ }
}

fs.writeFileSync(outFile, output);
console.log(`Wrote dist/mailcraft-editor.bundle.js (${files.length} modules, ${Buffer.byteLength(output)} bytes) -- ${note}`);
